#!/usr/bin/env bash
#
# Removes local, git-ignored run artifacts that accumulate under normal use -
# allure-results/, allure-report/, test-output/, logs/, reports/ (see .gitignore's
# "generated at runtime" section - none of these are ever committed, and every one
# is regenerated by the next `mvn test`, so deleting them is always safe).
#
# Usage:
#   scripts/clean-local.sh          # remove run artifacts only
#   scripts/clean-local.sh --all    # also run `mvn clean` (removes target/ too)

set -euo pipefail

cd "$(dirname "$0")/.."

RUN_ARTIFACT_DIRS=(allure-results allure-report test-output logs reports)

for dir in "${RUN_ARTIFACT_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        rm -rf "$dir"
        echo "Removed $dir/"
    fi
done

if [[ "${1:-}" == "--all" ]]; then
    echo "Running mvn clean (removes target/)..."
    mvn -q clean
fi

echo "Done."
